import Head from 'next/head'
import {useEffect, useState} from 'react'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import {Product} from '../interfaces/interface'
import ProductCard from '../components/ProductCard/ProductCard';
interface ComponentProps {
  products:Product[]
}
export default function Home(props:ComponentProps) {
  const [products, setproducts] = useState<Product[]>(props.products)

  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <div className='row'>
          <div className='col-sm-12'>
            <h1>Product List</h1>
          </div>
        </div>
        <div className='row'>
         {props.products.map((p,i)=><div key={i} className='col-sm-4'>
            <ProductCard product={p} />
          </div>)} 
        </div>
      </main>

    </div>
  )
}


export async function getStaticProps() {
  // Get external data from the file system, API, DB, etc.
  const data = await fetch('https://dummyjson.com/products').then(res => res.json())
  
  // The value of the `props` key will be
  //  passed to the `Home` component
  return {
    props: {
      products:data.products
    }
  }
}